name: Get Data

on:
  schedule:
    - cron:  '*/3 * * * *'
  push:
    branches: [ main ]

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
        env: 
          MY_GITHUB_API_TOKEN: ${{secrets.MY_GITHUB_API_TOKEN}}
      - run: npm i
      - run: npm run get 
        
